ltitle: SOE THIDA PO # your name (or website title) here
logo: "/images/eclip_logo.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

**AI/ML Enthusiast** | 8+ years in Web & Mobile App Development | Graduate Certificate, AI & ML (UT Austin)

  <br> 
  Dev experience in dynamic environments across Myanmar and Japan—skilled in Python, Kotlin, and AI-integrated solutions.  
Currently combining my passion for AI with real-world applications in both app development and AI/ML systems.
  <br>

   <br> 
  <a href="https://www.linkedin.com/in/soulthidapo/">[LinkedIn]</a> 
   <br> 
  <a href="https://github.com/soulthidapo">[GitHub]</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
