ltitle: SOE THIDA PO # your name (or website title) here
logo: "/images/eclip_logo.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  I have experienced in Web and Mobile development in Myanmar and Japan.
  <br> 
  My skills encompass Web and Mobile application(Android and iOS Development) using Kotlin and Swift.
  <br>
  <a href="https://www.linkedin.com/in/soulthidapo/">View My LinkedIn Profile</a> 
  <a href="https://github.com/soulthidapo">View My Github</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
