title: SOE THIDA PO # your name (or website title) here
logo: "/images/IMG_0191.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  I have almost 8+years experienced in software development fields in Myanmar and Japan.
  I have exceptional technical experience in software development.

  <br>
  My skills also encompass Web application project support and strategy.
  Moreover, I am eager to pursue a successful career in iOS Mobile Application.
  <br><br>
  <a href="https://www.linkedin.com/in/soulthida-po-8a8850120/">View My LinkedIn Profile</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
