title: SOE THIDA PO # your name (or website title) here
logo: "/images/IMG_0191.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About Me
  I am enthusiastic and completed a Bachelor of Computer Science(2007-2010). 
  I have exceptional technical experience in software development.

  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/soulthida-po-8a8850120/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
